<script>
    $(document).ready(function(){
   
        $("#prioridade-td-chamado").editInPlace({       
            url: "<?php echo $this->url('helpdesk/changeprioridade',array('setor'=>$this->setor))?>",
            field_type: "select",
            select_options: "<?php echo $this->prioridades; ?>", 
            params:"chamado=<?php echo $this->id ?>&member=<?php echo $this->member ?>&setor=<?php echo $chamado->getSetor_destino_fk()->getSetor() ?>&sector=<?php echo $this->setor?>",
            success:function(data){          
                var result = JSON.parse(data);
                if(result.previsao!='undefined')
                {
                    $("#prioridade-td-chamado").html(result.value);
                    $("#previsao").html(result.previsao);
                }
                else
                {
                    $("#prioridade-td-chamado").html(result.value);
                }                
            }
        });   
})

</script>
<table class="table table-striped table-bordered">
    <?php 
  
    $pertence = (($this->store['displayname'] == $chamado->getAutor()  && $chamado->getStatuschamado_fk()->getStatus() != 'Fechado') || ($this->store['departamento'] == strtoupper($chamado->getSetor_destino_fk()->getSetor())) && $chamado->getStatuschamado_fk()->getStatus() != 'Fechado') ? true : false; ?>
    <tbody>
        <tr>
            <th>Inicio</th>
            <th width="<?php echo $pertence  ? '70%' : '80%'; ?>"><?php echo  $chamado->getTitulo(); ?></th>

            <?php if ($pertence): ?><th width="10%">
                <a class="btn" title="Responder" href="<?php echo $this->url('helpdesk/chamado-resposta', array('id' => $chamado->getIdchamado(),'setor'=>$this->setor)); ?>"><i class="icon-share-alt"></i></a>
                <?php if ($pertence): ?> <form action="<?php echo $this->url('helpdesk/fechar', array('chamado' => $chamado->getIdchamado(),'setor'=>$this->setor)); ?>" method="post"><button type="submit" class="btn" title="Fechar" href="#"><i class="icon-remove"></i></button><input type="hidden" name="chamado" value="<?php echo $chamado->getIdchamado()?>"><input type="hidden" name="setor" value="<?php echo $setor;?>"></form>  <?php endif; ?>
            </th><?php endif; ?>
        </tr>

        <tr>
            <td><?php echo $chamado->getDatainicio(); ?></td>
            <td rowspan="11" colspan="2"><?php echo nl2br($chamado->getDescricao()); ?></td>
        </tr>
        <tr>
            <th>Previsão</th>
        </tr>
        <tr>
            <td id="previsao"><?php echo $chamado->getPrevisao(); ?> </td>
        </tr>
        <tr>
            <th>Setor solicitante</th>
        </tr>
        <tr>
            <td><?php echo $chamado->getSetor_origem_fk(); ?> </td>
        </tr>
        <tr>
            <th>Prioridade</th>
        </tr>
        <tr>
            <td id="prioridade-td-chamado"><?php echo $chamado->getPrioridade_fk()->getPrioridade(); ?> </td>
        </tr>
        <tr>
            <th>Autor</th>
        </tr>
        <tr>
            <td><?php echo $chamado->getAutor(); ?> </td>
        </tr>
        <tr>
            <td>Arquivo: <?php echo $chamado->getArquivo() ? "<a href='{$chamado->getArquivo()}' class='btn btn-success'><i class='icon-download-alt icon-white'></i></a>" : "Nenhum"; ?> </td>
        </tr>



    </tbody>

</table>
<?php if ($resposta): ?>
    <?php foreach ($resposta as $r): ?>
        <table class="table table-striped table-bordered">
            <tbody>
                <tr>
                    <th>Data da resposta</th>
                    <th width="80%"><?php echo $r->getAutor(); ?></th>

                  
                </tr>

                <tr>
                    <td><?php echo $r->getRegistro(); ?></td>
                    <td rowspan="2" colspan="2"><?php echo nl2br($r->getResposta()); ?></td>
                </tr>

                <tr>
                    <td>Arquivo: <?php echo $r->getArquivo() ? "<a href='{$r->getArquivo()}' class='btn btn-success'><i class='icon-download-alt icon-white'></i></a>" : "Nenhum"; ?> </td>
                </tr>



            </tbody>

        </table>
    <?php endforeach; ?>
<?php endif; ?>