<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Chamado aberto</title>
    </head>
    <body>
        <h1>Chamado aberto</h1>
        <?php echo $this->sujeito?>,<br/>
        <p>Voc&ecirc; acaba de abrir o chamado "<?php echo $this->titulo?>", com o seguinte texto:<br/><br/>
        <?php echo $this->conteudo?>
        </p>
        
        <p>Muito Obrigado</p>
        <p>Para acomapanhar o seu chamado clique no link abaixo:<br/><br/>
        <a href="http://irm.intranet<?php echo $this->url('helpdesk/chamado',array('setor'=>$this->setor,'chamado'=>$this->chamado))?>"><?php echo $this->titulo?></a><br/><br/></p>
        <hr/>
        Departamento de T.I.<br/><br/>
        &copy; <?php echo date('Y');?> IRM Services. Todos os direitos reservados.
    </body>
</html>
