<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" type="text/css"/>
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
<link rel="stylesheet" href="/js/chosen.css" type="text/css"/>

<script src="/js/chosen.jquery.min.js"></script>

<script>
    $(document).ready(function() {

        $("select").chosen();
    });
</script>

<?php

if (isset($this->form)) {
    $form = $this->form;

    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
}
if (isset($this->chamados_abertos)) {
    ?>
    <div class="alert alert-error">
    <strong>Erro</strong>: Antes de prosseguir é necessário que responda a avaliação de cada chamado abaixo!
    </div>
<ul>
    <?php
 foreach($this->chamados_abertos as $chamado)
 {?>
   <li> <a href="http://irm.intranet<?php echo $this->url('helpdesk/chamado/avaliar-chamado',array('setor'=>$this->setor,'chamado'=>$chamado->getIdchamado()))?>"><?php echo $chamado->getTitulo()?></a></li>
 <?php }
}
?>