<script src="/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function() {
        $("table a").tooltip();
        $("#tabela").dataTable();
    });
</script>
<style>
    .dataTables_filter,.dataTables_length{
        width:40%;
        float:left;
    }
    #tabela_info{
        width:45%;
        float:left;
    }
    #tabela
    {
        width:100%;
        float:left;
    }
    #tabela th
    {
        cursor: pointer;
    }

    #tabela_paginate{
        float:left;
        width:40%;
    }
    #tabela_paginate a{
        float:left;
        width:20%;
        cursor: pointer;
    }
</style>
<?php if ($this->messages): ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>       
        <?php foreach ($this->messages as $messages): ?>
            <strong>Success!</strong> <?php echo $messages ?>       
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<table id="tabela" class="table table-striped table-bordered table-hover">
    <thead>         
        <tr>
            <th>Item de avaliação</th>
            <th>Descrição</th>
            <th>Setor</th>
            <th>Opções</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $setor): ?>
            <tr>
                <td><?php echo $setor->itemavaliacaonome; ?></td>
                <td><?php echo $setor->descricao; ?></td>
                <td><?php echo $setor->getSetor_fk()->getSetor(); ?></td>

                <td> <a class="btn" href="<?php echo $this->url('item-avaliacao-chamado/store', array('id'=>$setor->getIditemavaliacaochamado(),'setor'=>$this->setor)); ?>"><i class="icon-pencil"></i> Edit</a>
                 <a class="btn btn-danger" href="<?php echo $this->url('item-avaliacao-chamado/delete', array('id'=>$setor->getIditemavaliacaochamado(),'setor'=>$this->setor)); ?>"><i class="icon-trash icon-white"></i> Delete</a></td>
            </tr>
        <?php endforeach; ?>
    <tfoot>
        <tr>
            
            <td colspan="4">  <a class="btn btn-primary" href="<?php echo $this->url('item-avaliacao-chamado/store', array('setor'=>$this->setor)); ?>"><i class="icon-plus icon-white"></i> Create</a></td>
        </tr>
    </tfoot>
</tbody>

</table>