<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle( $this->translate('IRM Net'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink()
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->appendFile('http://code.jquery.com/ui/i18n/jquery.ui.datepicker-pt-BR.js')
                ->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js');
        ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">

                <div class="nav-collapse collapse">

<?php if($nivel !='guest')echo $this->navigation('Navigation')->menu()->setAcl($acl)->setRole($nivel)->setPartial(array('partials/navigation.phtml', 'default'))->render();
$this->nivel = $nivel;
?>


                </div>
            </div>
        </div>
        <div class="container">
<?php echo $this->content; ?>
   
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y'); ?> IRM Services - Todos os direitos reservados.</p>
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>
